name: Nuget Package Deploy

on: 
 push:
   branches: 
     - AndroidX
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2     
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Nuget
      run: nuget restore  XamarinToolTip/XamarinAndroidToolTips.csproj
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with dotnet
      run: msbuild XamarinToolTip/XamarinAndroidToolTips.csproj -property:Configuration=Release
    - name: Pack with dotnet
      run: nuget pack XamarinAndroidToolTips.nuspec
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
